# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Actor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_actor: int=None, nombre: str=None, apellidos: str=None, fecha_nac: date=None, imagen_url: str=None, descripcion: str=None):  # noqa: E501
        """Actor - a model defined in Swagger

        :param id_actor: The id_actor of this Actor.  # noqa: E501
        :type id_actor: int
        :param nombre: The nombre of this Actor.  # noqa: E501
        :type nombre: str
        :param apellidos: The apellidos of this Actor.  # noqa: E501
        :type apellidos: str
        :param fecha_nac: The fecha_nac of this Actor.  # noqa: E501
        :type fecha_nac: date
        :param imagen_url: The imagen_url of this Actor.  # noqa: E501
        :type imagen_url: str
        :param descripcion: The descripcion of this Actor.  # noqa: E501
        :type descripcion: str
        """
        self.swagger_types = {
            'id_actor': int,
            'nombre': str,
            'apellidos': str,
            'fecha_nac': date,
            'imagen_url': str,
            'descripcion': str
        }

        self.attribute_map = {
            'id_actor': 'id_actor',
            'nombre': 'nombre',
            'apellidos': 'apellidos',
            'fecha_nac': 'fecha_nac',
            'imagen_url': 'imagen_url',
            'descripcion': 'descripcion'
        }
        self._id_actor = id_actor
        self._nombre = nombre
        self._apellidos = apellidos
        self._fecha_nac = fecha_nac
        self._imagen_url = imagen_url
        self._descripcion = descripcion

    @classmethod
    def from_dict(cls, dikt) -> 'Actor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Actor of this Actor.  # noqa: E501
        :rtype: Actor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_actor(self) -> int:
        """Gets the id_actor of this Actor.


        :return: The id_actor of this Actor.
        :rtype: int
        """
        return self._id_actor

    @id_actor.setter
    def id_actor(self, id_actor: int):
        """Sets the id_actor of this Actor.


        :param id_actor: The id_actor of this Actor.
        :type id_actor: int
        """

        self._id_actor = id_actor

    @property
    def nombre(self) -> str:
        """Gets the nombre of this Actor.


        :return: The nombre of this Actor.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """Sets the nombre of this Actor.


        :param nombre: The nombre of this Actor.
        :type nombre: str
        """

        self._nombre = nombre

    @property
    def apellidos(self) -> str:
        """Gets the apellidos of this Actor.


        :return: The apellidos of this Actor.
        :rtype: str
        """
        return self._apellidos

    @apellidos.setter
    def apellidos(self, apellidos: str):
        """Sets the apellidos of this Actor.


        :param apellidos: The apellidos of this Actor.
        :type apellidos: str
        """

        self._apellidos = apellidos

    @property
    def fecha_nac(self) -> date:
        """Gets the fecha_nac of this Actor.


        :return: The fecha_nac of this Actor.
        :rtype: date
        """
        return self._fecha_nac

    @fecha_nac.setter
    def fecha_nac(self, fecha_nac: date):
        """Sets the fecha_nac of this Actor.


        :param fecha_nac: The fecha_nac of this Actor.
        :type fecha_nac: date
        """

        self._fecha_nac = fecha_nac

    @property
    def imagen_url(self) -> str:
        """Gets the imagen_url of this Actor.


        :return: The imagen_url of this Actor.
        :rtype: str
        """
        return self._imagen_url

    @imagen_url.setter
    def imagen_url(self, imagen_url: str):
        """Sets the imagen_url of this Actor.


        :param imagen_url: The imagen_url of this Actor.
        :type imagen_url: str
        """

        self._imagen_url = imagen_url

    @property
    def descripcion(self) -> str:
        """Gets the descripcion of this Actor.


        :return: The descripcion of this Actor.
        :rtype: str
        """
        return self._descripcion

    @descripcion.setter
    def descripcion(self, descripcion: str):
        """Sets the descripcion of this Actor.


        :param descripcion: The descripcion of this Actor.
        :type descripcion: str
        """

        self._descripcion = descripcion
