# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ContenidoGenero(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, id_contenido: int=None, id_genero: int=None):  # noqa: E501
        """ContenidoGenero - a model defined in Swagger

        :param id: The id of this ContenidoGenero.  # noqa: E501
        :type id: int
        :param id_contenido: The id_contenido of this ContenidoGenero.  # noqa: E501
        :type id_contenido: int
        :param id_genero: The id_genero of this ContenidoGenero.  # noqa: E501
        :type id_genero: int
        """
        self.swagger_types = {
            'id': int,
            'id_contenido': int,
            'id_genero': int
        }

        self.attribute_map = {
            'id': 'id',
            'id_contenido': 'id_contenido',
            'id_genero': 'id_genero'
        }
        self._id = id
        self._id_contenido = id_contenido
        self._id_genero = id_genero

    @classmethod
    def from_dict(cls, dikt) -> 'ContenidoGenero':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ContenidoGenero of this ContenidoGenero.  # noqa: E501
        :rtype: ContenidoGenero
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ContenidoGenero.


        :return: The id of this ContenidoGenero.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ContenidoGenero.


        :param id: The id of this ContenidoGenero.
        :type id: int
        """

        self._id = id

    @property
    def id_contenido(self) -> int:
        """Gets the id_contenido of this ContenidoGenero.


        :return: The id_contenido of this ContenidoGenero.
        :rtype: int
        """
        return self._id_contenido

    @id_contenido.setter
    def id_contenido(self, id_contenido: int):
        """Sets the id_contenido of this ContenidoGenero.


        :param id_contenido: The id_contenido of this ContenidoGenero.
        :type id_contenido: int
        """

        self._id_contenido = id_contenido

    @property
    def id_genero(self) -> int:
        """Gets the id_genero of this ContenidoGenero.


        :return: The id_genero of this ContenidoGenero.
        :rtype: int
        """
        return self._id_genero

    @id_genero.setter
    def id_genero(self, id_genero: int):
        """Sets the id_genero of this ContenidoGenero.


        :param id_genero: The id_genero of this ContenidoGenero.
        :type id_genero: int
        """

        self._id_genero = id_genero
