# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ContenidoActor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, id_contenido: int=None, id_actor: int=None):  # noqa: E501
        """ContenidoActor - a model defined in Swagger

        :param id: The id of this ContenidoActor.  # noqa: E501
        :type id: int
        :param id_contenido: The id_contenido of this ContenidoActor.  # noqa: E501
        :type id_contenido: int
        :param id_actor: The id_actor of this ContenidoActor.  # noqa: E501
        :type id_actor: int
        """
        self.swagger_types = {
            'id': int,
            'id_contenido': int,
            'id_actor': int
        }

        self.attribute_map = {
            'id': 'id',
            'id_contenido': 'id_contenido',
            'id_actor': 'id_actor'
        }
        self._id = id
        self._id_contenido = id_contenido
        self._id_actor = id_actor

    @classmethod
    def from_dict(cls, dikt) -> 'ContenidoActor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ContenidoActor of this ContenidoActor.  # noqa: E501
        :rtype: ContenidoActor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ContenidoActor.


        :return: The id of this ContenidoActor.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ContenidoActor.


        :param id: The id of this ContenidoActor.
        :type id: int
        """

        self._id = id

    @property
    def id_contenido(self) -> int:
        """Gets the id_contenido of this ContenidoActor.


        :return: The id_contenido of this ContenidoActor.
        :rtype: int
        """
        return self._id_contenido

    @id_contenido.setter
    def id_contenido(self, id_contenido: int):
        """Sets the id_contenido of this ContenidoActor.


        :param id_contenido: The id_contenido of this ContenidoActor.
        :type id_contenido: int
        """

        self._id_contenido = id_contenido

    @property
    def id_actor(self) -> int:
        """Gets the id_actor of this ContenidoActor.


        :return: The id_actor of this ContenidoActor.
        :rtype: int
        """
        return self._id_actor

    @id_actor.setter
    def id_actor(self, id_actor: int):
        """Sets the id_actor of this ContenidoActor.


        :param id_actor: The id_actor of this ContenidoActor.
        :type id_actor: int
        """

        self._id_actor = id_actor
