# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Episodio(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_episodio: int=None, id_contenido: int=None, num_temporada: int=None, num_episodio: int=None, titulo: str=None, descripcion: str=None, duracion: int=None, stream_url: str=None):  # noqa: E501
        """Episodio - a model defined in Swagger

        :param id_episodio: The id_episodio of this Episodio.  # noqa: E501
        :type id_episodio: int
        :param id_contenido: The id_contenido of this Episodio.  # noqa: E501
        :type id_contenido: int
        :param num_temporada: The num_temporada of this Episodio.  # noqa: E501
        :type num_temporada: int
        :param num_episodio: The num_episodio of this Episodio.  # noqa: E501
        :type num_episodio: int
        :param titulo: The titulo of this Episodio.  # noqa: E501
        :type titulo: str
        :param descripcion: The descripcion of this Episodio.  # noqa: E501
        :type descripcion: str
        :param duracion: The duracion of this Episodio.  # noqa: E501
        :type duracion: int
        :param stream_url: The stream_url of this Episodio.  # noqa: E501
        :type stream_url: str
        """
        self.swagger_types = {
            'id_episodio': int,
            'id_contenido': int,
            'num_temporada': int,
            'num_episodio': int,
            'titulo': str,
            'descripcion': str,
            'duracion': int,
            'stream_url': str
        }

        self.attribute_map = {
            'id_episodio': 'id_episodio',
            'id_contenido': 'id_contenido',
            'num_temporada': 'num_temporada',
            'num_episodio': 'num_episodio',
            'titulo': 'titulo',
            'descripcion': 'descripcion',
            'duracion': 'duracion',
            'stream_url': 'stream_url'
        }
        self._id_episodio = id_episodio
        self._id_contenido = id_contenido
        self._num_temporada = num_temporada
        self._num_episodio = num_episodio
        self._titulo = titulo
        self._descripcion = descripcion
        self._duracion = duracion
        self._stream_url = stream_url

    @classmethod
    def from_dict(cls, dikt) -> 'Episodio':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Episodio of this Episodio.  # noqa: E501
        :rtype: Episodio
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_episodio(self) -> int:
        """Gets the id_episodio of this Episodio.


        :return: The id_episodio of this Episodio.
        :rtype: int
        """
        return self._id_episodio

    @id_episodio.setter
    def id_episodio(self, id_episodio: int):
        """Sets the id_episodio of this Episodio.


        :param id_episodio: The id_episodio of this Episodio.
        :type id_episodio: int
        """

        self._id_episodio = id_episodio

    @property
    def id_contenido(self) -> int:
        """Gets the id_contenido of this Episodio.


        :return: The id_contenido of this Episodio.
        :rtype: int
        """
        return self._id_contenido

    @id_contenido.setter
    def id_contenido(self, id_contenido: int):
        """Sets the id_contenido of this Episodio.


        :param id_contenido: The id_contenido of this Episodio.
        :type id_contenido: int
        """

        self._id_contenido = id_contenido

    @property
    def num_temporada(self) -> int:
        """Gets the num_temporada of this Episodio.


        :return: The num_temporada of this Episodio.
        :rtype: int
        """
        return self._num_temporada

    @num_temporada.setter
    def num_temporada(self, num_temporada: int):
        """Sets the num_temporada of this Episodio.


        :param num_temporada: The num_temporada of this Episodio.
        :type num_temporada: int
        """

        self._num_temporada = num_temporada

    @property
    def num_episodio(self) -> int:
        """Gets the num_episodio of this Episodio.


        :return: The num_episodio of this Episodio.
        :rtype: int
        """
        return self._num_episodio

    @num_episodio.setter
    def num_episodio(self, num_episodio: int):
        """Sets the num_episodio of this Episodio.


        :param num_episodio: The num_episodio of this Episodio.
        :type num_episodio: int
        """

        self._num_episodio = num_episodio

    @property
    def titulo(self) -> str:
        """Gets the titulo of this Episodio.


        :return: The titulo of this Episodio.
        :rtype: str
        """
        return self._titulo

    @titulo.setter
    def titulo(self, titulo: str):
        """Sets the titulo of this Episodio.


        :param titulo: The titulo of this Episodio.
        :type titulo: str
        """

        self._titulo = titulo

    @property
    def descripcion(self) -> str:
        """Gets the descripcion of this Episodio.


        :return: The descripcion of this Episodio.
        :rtype: str
        """
        return self._descripcion

    @descripcion.setter
    def descripcion(self, descripcion: str):
        """Sets the descripcion of this Episodio.


        :param descripcion: The descripcion of this Episodio.
        :type descripcion: str
        """

        self._descripcion = descripcion

    @property
    def duracion(self) -> int:
        """Gets the duracion of this Episodio.


        :return: The duracion of this Episodio.
        :rtype: int
        """
        return self._duracion

    @duracion.setter
    def duracion(self, duracion: int):
        """Sets the duracion of this Episodio.


        :param duracion: The duracion of this Episodio.
        :type duracion: int
        """

        self._duracion = duracion

    @property
    def stream_url(self) -> str:
        """Gets the stream_url of this Episodio.


        :return: The stream_url of this Episodio.
        :rtype: str
        """
        return self._stream_url

    @stream_url.setter
    def stream_url(self, stream_url: str):
        """Sets the stream_url of this Episodio.


        :param stream_url: The stream_url of this Episodio.
        :type stream_url: str
        """

        self._stream_url = stream_url
